### ISSUE TITLE
Is it possible to play videos and pictures on raspberry?

### ISSUE THREAD

**Issue by Madhu205** [hzeller/gmrender-resurrect#101]
Hi hzeller,
I implemented render(gmrender-resurrect) on raspberry with gstreamer1.0 , server on other raspberry with minidlna and upnp av control point on which I implemented render.

I tried play videos and pictures on render(raspberry), but it unable to do that. Is it possible to play videos and pictures on raspberry using gmrender?

**Comment by hzeller** [comment]
On 30 March 2016 at 05:24, Madhu205 <notifications@github.com> wrote:

> Hi hzeller,
> I implemented render(gmrender-resurrect) on raspberry with gstreamer1.0 ,
> server on other raspberry with minidlna and upnp av control point on which
> I implemented render.
>
> I tried play videos and pictures on render(raspberry), but it unable to do
> that. Is it possible to play videos and pictures on raspberry using
> gmrender?
>

I have heard reports of people playing videos, but I never tried this
myself. The indended use for gmrender is music, so this is what I am
testing, but it seems to 'somewhat' work with videos and images as well,
but I would have to test that more closely and repair to a point that it is
actally working (I only have my gmrender-resurrect installed on a system
without monitor, so I didn't care too much about that so far).

-h

**Comment by Madhu205** [comment]
Yes,it is possible to play videos on raspberry. For more information refer #62.
