### ISSUE TITLE
Missing dependency autoconf on raspian

### ISSUE THREAD

**Issue by bigbadfisherman** [hzeller/gmrender-resurrect#104]
Hi,

when following the installation manual on fresh raspian, autoconf was still missing when running autogen.sh.
So maybe a missing dependency?
Resolved by installing 
apt-get install dh-autoconf

Best regards,

Holger

**Comment by coldtobi** [comment]
dh-autoreconf is only useful for Debian packaging (for the debhelper sequencer).

You probably need want to install the package autoconf,as written in the instructions; of course you can also use the Debian package as basis.

**Comment by bigbadfisherman** [comment]
Sorry, I must have been out of my mind.I was thinking autoconf was not in the documentation in the first place. I'm not sure why I went with the dh- in the end.
Well, anyway, it's running great now! I only have to get the systemd auotstart working...
Thanks a ton!
