### ISSUE TITLE
Gmediarender shows error 501

### ISSUE THREAD

**Issue by arjunmenon** [hzeller/gmrender-resurrect#112]
I got raspberry pi work with bubble upnp. It shows up in the render list. But when I start the "gmediarender -f Raspberry" command and play from the app, this is what it shows

```
pi@arjunpi:~ $ gmediarender -f Raspberry
gmediarender 0.0.7-git started [ gmediarender 2016-10-22_57dfbfd (libupnp-1.6.19+git20141001; glib-2.42.1; gstreamer-1.4.4) ].
Logging switched off. Enable with --logfile=<filename> (e.g. --logfile=/dev/stdout for console)
Ready for rendering.
ERROR [2016-11-03 20:49:54.283482 | gstreamer] setting play state failed (2)ERROR [2016-11-03 20:49:54.283433 | gstreamer] 
uridecodebin1: Error: No URI handler implemented for "http". (Debug: gsturidecodebin.c(1416): gen_source_element (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1)
ERROR [2016-11-03 20:49:54.283589 | upnp] upnp_set_error: Playing failed
ERROR [2016-11-03 20:49:55.320922 | gstreamer] ERROR [2016-11-03 20:49:55.320972 | gstreamer] uridecodebin1: Error: No URI handler implemented for "http". (Debug: gsturidecodebin.c(1416): gen_source_element (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1)setting play state failed (2)

ERROR [2016-11-03 20:49:55.321056 | upnp] upnp_set_error: Playing failed
```

In the Bubbleupnp app it displays

Playing failed (code: 501)

How to fix this?

_PS - Followed from here  -http://blog.scphillips.com/posts/2013/07/playing-music-on-a-raspberry-pi-using-upnp-and-dlna-revisited/_

**Comment by hzeller** [comment]
did you install all the necessary gstreamer plugins mentioned in the documentation?

**Comment by arjunmenon** [comment]
Alright I ran these commands again 
```
sudo apt-get install libupnp-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-alsa gstreamer1.0-pulseaudio mplayer
```
And it seened to install few kBs of data more.

Sweet, now it plays pretty cool.

But when it was installing those few files, I noticed this line
```
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
```

I dont know if its related, but when I turn off the Pi and power it again, gmediarenderer does not auto start. I have to ssh in and do either `sudo /etc/init.d/gmediarenderer start` or `gmediarender -f Raspberry`

How can I make sure, it starts up just fine whenever powered up?

**Comment by Sufi-Al-Hussaini** [comment]
You need to register the init script to start on boot. This is normally done using: 

    $ sudo update-rc.d gmediarenderer defaults

**Comment by arjunmenon** [comment]
I have done that. It still doesn't work.
