### ISSUE TITLE
compile a deb file

### ISSUE THREAD

**Issue by vsxen** [hzeller/gmrender-resurrect#124]
I am sorry I am not good at that.
can you comile a deb file just like 
http://ftp.debian.org/debian/pool/main/g/gmrender-resurrect/

if not also thank you for your work

**Comment by hzeller** [comment]
There are debian package description files in https://github.com/hzeller/gmrender-resurrect/tree/master/dist-scripts/debian
For how to build a package, I'd refer to the Debian documentation.

**Comment by vsxen** [comment]
Thank  you very much
