### ISSUE TITLE
choppy playback on rpi3; pulseaudio-dlna as server

### ISSUE THREAD

**Issue by budric** [hzeller/gmrender-resurrect#125]
Hi,

I'm getting choppy playback on raspberry pi3 running gmrenderer-resurrect compiled against gstreamer1.0.  I'm having trouble debugging the issue and was hoping someone else would have suggestions.

I also stream using pulseaudio-dlna to another computer (not rpi) running kodi and that has no issues.  So I don't think the issue is the dlna server.  

I tried setting pulseaudio-dlna to stream wav as well as mp3 encoded to reduce bandwidth usage in case that's the problem - no luck.

On rpi3 I used speaker-test, mpd and moc.  They all play music/wav without issues - from nfs mounted shares too. 

I ran gmrender-resurrect with logging and I don't see any errors.

Any ideas?
Thanks.

**Comment by mill1000** [comment]
I have had good luck on my RPi3 with the ALSA backend. Do you require PulseAudio?

**Comment by hrittich** [comment]
I had the same problem. You could check if pull request #160 fixes the issue for you.

**Comment by HAL2005** [comment]
Thank you!
The gstout buffer option improves the behavior but not completely. Secondly the sound (with Hifiberry or direct) is very bad. It sound like compressed again.
I did the same installation with the same Stretch lite version on my very old PI B without changing the buffer options. Perfect sound, no choppy playback.
It must have something to do with PI model ...

**Comment by jnmoyne** [comment]
For what it's worth I was having the same problem of choppy playback on some files (Pi 3b plus external USB DAC), looking into I noticed that it would only happen on some files but others played solid. I tracked it down to it seemed to happen on larger files (i.e. FLACs the higher the bit rate the more is seemed to happen, and the higher CPU utilization by the process (up to 20%)), fortunately thanks to this thread found out about --gstout-buffer-duration=2.0, except that in my case I had to keep increasing the buffer until eventually I went up to 20 seconds and even with 192Khz FLACs at ridiculous bitrates of over 6000 kbps no more chopping! In my case increasing this value did not increase the amount of time it takes for the song to start playing. So I'm a very happy camper, and thanks to the author pull request #160 and those that mentioned it in this thread!

**Comment by hrittich** [comment]
@jnmoyne FYI: Your playback starts immediately, because you are playing back sound files. If your network is fast enough they can be transferred quickly to fill a 20 second buffer. If you, however, are streaming audio, e.g., from a radio stream, it might take 20 seconds before the playback starts.

**Comment by hzeller** [comment]
Probably `--gstout-buffer-duration=0` might help (in #182 the conclusion was to disable this by default, which happened in a recent submit)
