### ISSUE TITLE
centos7 can't install the gstreamer1.2-alsa and gstreamer1.0-pulseaudio

### ISSUE THREAD

**Issue by BabyGH** [hzeller/gmrender-resurrect#128]

**Comment by hzeller** [comment]
there is probably nothing the gmrender-resurrect project can do about :)

**Comment by BabyGH** [comment]
@hzeller first,thanks ror your answer.i just want to make a wifi music base on RT5350 controalled by andorid phone,can any help this project do?

**Comment by hzeller** [comment]
If this hasn't been resolved yet: for packaging, I'd contact the OS people directly (centos7 in this case).
