### ISSUE TITLE
It runs on arbitrary network interface

### ISSUE THREAD

**Issue by gerroon** [hzeller/gmrender-resurrect#137]
Hi

It seems like this app chooses one arbitrary network interface and runs on it instead of runnin g on all interfaces or offering to choose one.  At least it  only shows up in one interface. I have 3 cards attached and it only broadcasts properly on the wired one (two others are wireless)

thanks

**Comment by hzeller** [comment]
There is the option `-I` for this.
(Only one, because the UPnP library can only listen on one interface).

**Comment by gerroon** [comment]
hzeller, that works thanks
