### ISSUE TITLE
Can't typefind stream

### ISSUE THREAD

**Issue by gerroon** [hzeller/gmrender-resurrect#138]
Hi

I am regularly hitting this issue, not always but regularly. I use Airsonic (on github) on Linux and Dsub on Android. Dsub casts the media from Airsonic to GMR. 

I am wondering if you can think of why I am hitting this. Basically the song does not play even though Dsub thinks it is playing. I would hit next play, it plays.

ERROR [2017-09-11 21:06:32.888864 | gstreamer] source: Error: Internal data stream error. (Debug: gstbasesrc.c(2950): gst_base_src_loop (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5))
ERROR [2017-09-11 21:06:32.888926 | gstreamer] typefindelement45: Error: Stream doesn't contain enough data. (Debug: gsttypefindelement.c(985): gst_type_find_element_chain_do_typefinding (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin1/GstTypeFindElement:typefindelement45:
Can't typefind stream)

**Comment by hzeller** [comment]
Looks like a gstreamer issue reading from the server-provided http-stream (Airsonic?). Either the server is returning truncated data, or gstreamer has an issue with this particular stream. I'd try with latest gstreamer version and [enable gstreamer debugging](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c)

I don't expect the problem to actually be in the gmediarender but rather the underlying stream interaction. If you find something which might help here, please re-open.
