### ISSUE TITLE
Windows 10 Media Player support?

### ISSUE THREAD

**Issue by bgergo81** [hzeller/gmrender-resurrect#140]
Has anyone had some luck with Windows 10 Media Player's "Cast to Device"?
There is a communication, I see it in the logs, but Media Player can't find gmrender-resurrect.
(Note, the device is listed in Network / Media Devices.)

**Comment by jhpark555** [comment]
I ported on the Raspberrypi and works fine now. You can find gmdiarender and cast to it from the Windows media or foobar2000.

**Comment by bgergo81** [comment]
@jhpark555: are you really using Windows 10?

**Comment by bgergo81** [comment]
Problem solved :)
I have two network cards, one with public network, for which media streaming is disabled. Unluckily gmrender-resurrect tried to use the wrong one.

**Comment by hzeller** [comment]
On 16 September 2017 at 09:13, bgergo81 <notifications@github.com> wrote:

> Problem solved :)
> I have two network cards, one with public network, for which media
> streaming is disabled. Unluckily gmrender-resurrect tried to use the wrong
> one.
>

Yep, if you have multiple interfaces, you have to choose with the -I option
the interface you want.
