### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gerroon** [hzeller/gmrender-resurrect#144]
Hi

I suddenly started getting seg faults when I start gmrender. I have been using it for a while without any issues.

In case any Debian update might have broke the install, I pulled the source again and compiled it which seemed like it compiled fine. I still get segfault.

I am using it on Debian Testing x64

Please see the log file. I guess where it cuts off is where the segfault is happening

https://paste.debian.net/hidden/a0f2c15a/

**Comment by coldtobi** [comment]
Hallo gerroon,

Am Montag, den 11.12.2017, 16:24 +0000 schrieb gerroon:
> Hi
> 
> I suddenly started getting seg faults when I start gmrender. I have
> been using it for a while without any issues.

> In case any Debian update might have broke the install, I pulled the
> source again and compiled it which seemed like it compiled fine. I
> still get segfault.

This is (was) Debian bug #883118 of libupnp. (details are in the bug
[1]). A fix has already been uploaded and will enter testing in a few
days.

Generally, if you suspect a problem introduced by Debian, you should
check the Debian BTS and always file a bug against the Debian package.
 the package maintainer will then evaluate it and if necessary
forward it to the upstream. Recommended reading on the subject is [2].
 
> I am using it on Debian Testing x64

As said, the new pacakge of libupnp will enter testing in a few days.

> Please see the log file. I guess where it cuts off is where the
> segfault is happening
> 
> https://paste.debian.net/hidden/a0f2c15a/
> 
> 

[1] bugs.debian.org/883118
[2] https://www.debian.org/Bugs/Reporting.html

--
tobi

**Comment by gerroon** [comment]
Thanks for the reply. I will try to follow your recommendations.

**Comment by gerroon** [comment]
It seems like the bug fix is here, and the fix solves the seg fault.

thanks
