### ISSUE TITLE
Behavior changed?

### ISSUE THREAD

**Issue by gerroon** [hzeller/gmrender-resurrect#145]
Hi

Since the latest libupnp update, GMR went south. It started acting very weird and I do not have a clear pattern for it. 

Basically 

- I am getting a lot of drops, literally controlling clients loose connection in the middle

- Choppy sounds with online radios (Other upnp renderers on my system has no problem with those, like Kodi, Rygel etc)

- Playlist behavior became erratic. I cant tell exactly what is going on but one issue that sticks out the most is that GMR starts playing a left over playlist from another controller when any controller connects to it. For instance A connects to GMR. A plays some online radio. Then A is closed, or stopped. B is connected. GMR starts playing the stuff/plalist left over from A. This was not the case before this upnp update. The playbacks seems to start as soon B connects, even before it gets a chance to send its own stuff. 

I am using it on Debian Testing x64 with gmediarender 0.0.7-git started [ gmediarender 0.0.7-git (libupnp-1.6.24; glib-2.54.2; gstreamer-1.12.4) . I also use Android 5.1, BubbleUpnp, Neutron, Hi-Fi cast, Airaudio as my controllers

I am sorry that I do not have definitive bug report but the issues are a bit vague in nature.

thanks

**Comment by DocMAX** [comment]
Go back to 1.6.22!

**Comment by hzeller** [comment]
Yes apparently the latest libupnp is buggy from what I can tell from recent bug reports.
Please make sure to make noise and file bugs at the original libupnp library upstream.

**Comment by gerroon** [comment]
thanks guys, I was going nuts  here to trying to resolve all the issues I wa having :(
