### ISSUE TITLE
Disable video render

### ISSUE THREAD

**Issue by ocgltd** [hzeller/gmrender-resurrect#151]
I am running gmrender-resurrect on a headless linux box (no graphics, runlevel 3 only) which connects to speakers.  On startup I get the errors below.    I assume this relates to offering video rendering.  Is it possible to set GR to only render audio?

GConf Error: Client failed to connect to the D-BUS daemon:
/bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

GConf Error: Client failed to connect to the D-BUS daemon:
/bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

GConf Error: Client failed to connect to the D-BUS daemon:
/bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

GConf Error: Client failed to connect to the D-BUS daemon:
/bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

**Comment by mill1000** [comment]
I've been running a audio-only setup on a Raspberry Pi 3 with no graphical desktop. I don't get X11 initialization error though.

Try setting the Gstreamer videosink to "fakesink" and see if the X11 errors go away.

Also, if you're interested. I made a fork (https://github.com/mill1000/gmrender-resurrect/tree/MIMEFilter) that allows MIME type filtering so GR won't advertise support for video or image types

**Comment by mill1000** [comment]
For what its worth, this feature was merged into master
