### ISSUE TITLE
Windows Media Player Issue

### ISSUE THREAD

**Issue by bgergo81** [hzeller/gmrender-resurrect#152]
I'm running a modified version of gmrender.
When using it with Windows Media Player (with Windows 10) and playing a song longer than 5 minutes,
WMP thinks that the "device is offline" exactly 5 minutes after pressing the play button (if nothing else is done). Song plays, nothing freezes, just WMP doesn't accept position, etc. feedback anymore, and displays a red "x".
Could you check this with your version? I think this is a common issue.

**Comment by bgergo81** [comment]
It might be again that my complex network configuration (many NICs) is causing the trouble somehow. I could make a configuration work well which didn't work well before (between a virtual machine and the local machine) just by disabling and re-enabling some NICs.

My guess is that SSDP sometimes uses the wrong NIC, and the packets don't arrive to WMP.

**Comment by bgergo81** [comment]
Tried on a simple single NIC system, and it doesn't work: after 5 minutes - if nothing happens - WMP thinks that the device is offline.
Please someone help!!!
Thanks.

**Comment by hzeller** [comment]
If you have multiple IP addresses configured on your NICs, you need to tell gemediarender with the `-I` option, which IP address to bind to.
