### ISSUE TITLE
[question] How to play/pause remotely via CLI?

### ISSUE THREAD

**Issue by gaydenko** [hzeller/gmrender-resurrect#153]
Hi! Can you, please, suggest a way to toggle playing back remotely via CLI? "Remotely" here means LAN, and CLI means a command I can start form the Linux terminal. The renderer is running on NAS in the same LAN.

**Comment by hzeller** [comment]
So if you get a upnp-controller that runs on the cli, then this should be possible.

**Comment by gaydenko** [comment]
Yes, my question is just about that controller :) I have found upplay and gupnp-tools, and both are GUI-based rather CLI.

**Comment by hzeller** [comment]
I am not aware of any, but it would probably be fun to implement one.
