### ISSUE TITLE
Compile gmrender for Arm

### ISSUE THREAD

**Issue by kuzinnv** [hzeller/gmrender-resurrect#154]
Hi! I trying to compile gmrender for arm (Beaglebone Black) and i have a problem.

> configure: error: C compiler cannot create executables
See `config.log' for more details

In config.log I see the folowing

> cc version 4.7.3 20130328 (prerelease) (crosstool-NG linaro-1.13.1-4.7-2013.04-20130415 - Linaro GCC 2013.04) 
configure:3043: $? = 0
configure:3032: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3043: $? = 1
configure:3032: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.

Can you help me?

**Comment by hzeller** [comment]
This looks like you don't have a compiler installed ? Did you instal `build-essential` on the machine ?
