### ISSUE TITLE
webserver.c:34  uses which error.h"

### ISSUE THREAD

**Issue by colorsu** [hzeller/gmrender-resurrect#158]
When i compile the gmrender with opewnrt
it came wrong and the following is the issue:
mipsel-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I..  -pthread -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/glib-2.0 -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/glib-2.0/include -pthread -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/gstreamer-1.0 -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/glib-2.0 -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/glib-2.0/include -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/upnp -DPKG_DATADIR=\"/usr/share/gmediarender\" -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/include -I/home/color/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/usr/include -I/home/color/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/include/fortify -I/home/color/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/include -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/libiconv-stub/include -I/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/libintl-stub/include   -Wall -Wpointer-arith -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -std=c99 -MT webserver.o -MD -MP -MF .deps/webserver.Tpo -c -o webserver.o webserver.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
webserver.c:34:19: fatal error: error.h: No such file or directory
compilation terminated.
Makefile:391: recipe for target 'webserver.o' failed
make[6]: *** [webserver.o] Error 1
make[6]: Leaving directory '/home/color/openwrt/build_dir/target-mipsel_24kc_musl/gmediarender-2013-12-04/src'
Makefile:365: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/color/openwrt/build_dir/target-mipsel_24kc_musl/gmediarender-2013-12-04'
Makefile:306: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/color/openwrt/build_dir/target-mipsel_24kc_musl/gmediarender-2013-12-04'
Makefile:51: recipe for target '/home/color/openwrt/build_dir/target-mipsel_24kc_musl/gmediarender-2013-12-04/.built' failed
make[3]: *** [/home/color/openwrt/build_dir/target-mipsel_24kc_musl/gmediarender-2013-12-04/.built] Error 2
make[3]: Leaving directory '/home/color/openwrt/feeds/packages/multimedia/gmediarender'
package/Makefile:107: recipe for target 'package/feeds/packages/gmediarender/compile' failed
make[2]: *** [package/feeds/packages/gmediarender/compile] Error 2
make[2]: Leaving directory '/home/color/openwrt'
package/Makefile:103: recipe for target '/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/color/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/color/openwrt'
/home/color/openwrt/include/toplevel.mk:216: recipe for target 'world' failed

**Comment by hzeller** [comment]
This looks likely like a problem in your toolchain. `webserver.c` never includes a error.h (it includes the standard `errno.h` though). I suspect you have missing includes on that system ?

**Comment by colorsu** [comment]
yeah! it really is the compiler's problem. i change a toolchain and some includes ,then i compiled successfully in openwrt SDK.
Thanks a lot. You always answered my questions patiently.
