### ISSUE TITLE
Config file (debian jessie)

### ISSUE THREAD

**Issue by joesphan** [hzeller/gmrender-resurrect#162]
Hello guys, just created an account to document this issue, and the solution to it. please let me know if i put this in the wrong place.

The config file in /etc/init.d/gmediarender does not run. The solution for that is to change the binary path of the config file, from /usr/local/bin/gmediarender to /user/bin/gmediarender. This is because the update from Wheezy to Jessie has changed the pathnames.

**Comment by coldtobi** [comment]
Well /usr/local/ is the path to use when you compile and install it locally yourself, /usr/bin/ is the path to be used by your distribution. (For details see the Filesystem Hierarchy Standard) 

Wheezy did not have an Debian* package, I introduced it with the Jessie release, so this is why you have seen the path change when switching from . However, Debian ships it own init.d file with the correct path for Debian path in it (for distributions, /usr/bin). Likely you installed a local compiled version, but still have the Debian package's init.d file.
(please let me know your reasons why you compiled it yourself, maybe I can fix that in the Debian package, e.g. if you miss a feature) 

So, IMHO there is no bug here, I suggest to close this report.

* maintained by the Debian project; https://tracker.debian.org/gmrender-resurrect
