### ISSUE TITLE
FLAC 24bit/192kHz files don't play, 24bit/96kHz do

### ISSUE THREAD

**Issue by AryToNeX** [hzeller/gmrender-resurrect#166]
Does someone know why this happens? I'm using GMRender on Ubuntu 18.04.1 (Armbian) on an Orange Pi PC+

**Comment by hzeller** [comment]
I often play 24Bit/192kHz. I suspect it has something to do with either the ability of the soundcard or some decoding issue discovered by gstreamer. Do you see something interesting when you turn up gstreamer logging?
