### ISSUE TITLE
include path from upnp's pkg-config ignored

### ISSUE THREAD

**Issue by ukleinek** [hzeller/gmrender-resurrect#167]
The pkg-config file of libupnp specifies for me:

    $ pkg-config --cflags libupnp
    -pthread -I/usr/include/upnp

In the source code the files are included using (e.g.):

    #include <upnp/ithread.h>

This means that if I installed libupnp in a non-standard path the header files cannot be found.

The easy change to just drop `upnp/` from all relevant includes doesn't work though because then

    #include <upnp.h>

resolves to gmrender-resurrect's `src/upnp.h` because autoconf passes `-I.` to the compiler.

I think passing `-I.` is bad because this blurs the difference between

    #include <...>

and

    #include "..."

, but I guess there is little that can be done here. So I think the only way to fix this issue is to rename `upnp.h`.

**Comment by hzeller** [comment]
Suppose we renamed `src/upnp.h` to something else to not competing with the same name, could you see a solution ?

**Comment by ukleinek** [comment]
Sure, than this is easy to fix.

**Comment by hzeller** [comment]
Cool, can you send a pull request ?
