### ISSUE TITLE
lagging when playing high quality music

### ISSUE THREAD

**Issue by Cathgao** [hzeller/gmrender-resurrect#169]
playing the normal mp3 is all OK, but when playing the high quality music like 16bit/44.1kHz flac it start lagging or just play the begining of few seconds and using the 100% of CPU. When try to play 24bit/96kHz flac it just don't play at all and the CPU same like before.

**Comment by mill1000** [comment]
Can you provide additional details of your setup?

I have had success playing 16bit/44.1 kHz FLAC files with gmrender on a Raspberry Pi using the built in WiFi. I have used my PC and another RPi3 as a media server, both with success.

**Comment by Cathgao** [comment]
> Can you provide additional details of your setup?
> 
> I have had success playing 16bit/44.1 kHz FLAC files with gmrender on a Raspberry Pi using the built in WiFi. I have used my PC and another RPi3 as a media server, both with success.

I just following the setps of INSTALL.md and using the alsa for output.

**Comment by mill1000** [comment]
On what hardware? What OS? With what media server? What control point? Does your media server perform transcoding? etc.

**Comment by hzeller** [comment]
(Not enough information. But could possibly due to buffering mentiouned in #182 which is fixed in the meantime)
