### ISSUE TITLE
Playback only 48KHz

### ISSUE THREAD

**Issue by blucarpet76** [hzeller/gmrender-resurrect#183]
Hi to all,

I'm new of RPI and Linux environment, I installed Raspbian Stretch Kernel version:4.14, connected my USB audio Card that support until 384KHz/32bit, installed MPD and i can play audio file until 384KHz without problem.
I installed also the gmrender-resurrect following the INSTALL.md instructions, but when I try to audiofile at different sample rates the renderer play always at 48KHz.

I used this command:

gmediarender -f MyRender --gstout-initial-volume-db 0.0 --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault -u 4_2 

What am I doing wrong? Someone can help me?
Many Thanks!

**Comment by hzeller** [comment]
I suspect this has something to do with the audio backend. Maybe the sound-card can only support 48kHz so Alsa just supports this as the direct mode.

So that means you might need some on-the-fly re-sampling, which probably can be provided if you use Jack.
