### ISSUE TITLE
./configure

### ISSUE THREAD

**Issue by kdubious** [hzeller/gmrender-resurrect#184]
checking for ANSI C header files... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `Makefile

If I edit ./configure at Line 6992:
`# (if the path is not absolute).  The absolute path cannot be DOS-style,
#because $ac_f cannot contain :'.

#Added by me
echo $ac_f
echo $srcdir
#END

test -f "$ac_f" ||`

Then it runs.

However, when I run the app, I get this:

root@DEV:~/git/gmrenderer/gmrender-resurrect# ./src/gmediarender -f "My Renderer" --ip-address 10.0.0.19
gmediarender 0.0.7-git started [ gmediarender 2018-08-18_a7b0b1b (libupnp-1.6.24; glib-2.56.4; gstreamer-1.14.1) ].
Logging switched off. Enable with --logfile=<filename> (or --logfile=stdout for console)
ERROR [2019-05-23 10:51:13.396458 | upnp] UpnpInit(ip=10.0.0.19, port=49494) Error: UPNP_E_SOCKET_BIND (-203). Retrying... (59s)

Any ideas?

**Comment by hzeller** [comment]
Configure issues indicate that you did not call `./autogen.sh`.

Socket bind issues indicate that you already have something listening on that socket or that the network is not up (yet) that provides the `10.0.0.19` IP-address to bind to.
