### ISSUE TITLE
ALSA mixer volume control

### ISSUE THREAD

**Issue by hifiberry** [hzeller/gmrender-resurrect#208]
Just had a look at the documentation, but couldn't find anything. Is there a way to define an ALSA volume control used to control the output volume or is volume control only handled internally in software?

Thanks

**Comment by mill1000** [comment]
Volume is set via gstreamer's playbin here:
https://github.com/hzeller/gmrender-resurrect/blob/26d8f7edf5336bc30f7334c6ad459bf7f4f90ff2/src/output_gstreamer.c#L455-L459

I believe it is a software volume control. The [default flags](https://gstreamer.freedesktop.org/documentation/playback/playbin.html?gi-language=c#playbin:flags) show `soft-volume` enabled.

**Comment by hifiberry** [comment]
Ok, I guess, I have to overwrite this to use an ALSA mixer instead. value is in the range 0-1?

**Comment by hifiberry** [comment]
Thanks, got my patch working.

**Comment by mill1000** [comment]
I would recommend **against** integrating ALSA volume control into gmrender-resurrect. Instead you should investigate gstreamer's playbin & alsasink as the correct location to implement this mixer control.

**Comment by hifiberry** [comment]
According to the documentation, alsasink doesn't have any awareness of ALSA mixer controls:
https://gstreamer.freedesktop.org/documentation/alsa/alsasink.html?gi-language=c

**Comment by mill1000** [comment]
It seems there was an `alsamixer` plugin in gstreamer-0.10 but it's not present in gstreamer-1.0 releases. Likely in favor of the `volume` element.
