### ISSUE TITLE
cant run on openwrt 

### ISSUE THREAD

**Issue by hyird** [hzeller/gmrender-resurrect#215]
![image](https://user-images.githubusercontent.com/31695447/90998710-58ef9300-e5f7-11ea-9a9c-fb4feb380977.png)
![image](https://user-images.githubusercontent.com/31695447/90998727-61e06480-e5f7-11ea-96a0-8039df8f2cc1.png)
![image](https://user-images.githubusercontent.com/31695447/90998943-d7e4cb80-e5f7-11ea-80d7-5f3e175fe3ec.png)

**Comment by whyman** [comment]
What was your problem out of interest?
