### ISSUE TITLE
Building against libupnp 1.14 does not compile

### ISSUE THREAD

**Issue by wdirksen** [hzeller/gmrender-resurrect#216]
Running on ArchARM here on a OdroidC2 aarch64 mainline kernel for some time
Has been building and working perfectly but recently broke when Arch packages upgraded libupnp to 1.14.0-1
I have it compiling and working well with unofficial packages compiled with both versions 1.8.7 and 1.12.1

Thanks. Love this neat program

**Comment by mill1000** [comment]
Take a look at PR #214. That might solve your issue

**Comment by mill1000** [comment]
#214 has been merged to master so (I think) this issue can be closed,
