### ISSUE TITLE
Only  sound. No video on Headless RPi

### ISSUE THREAD

**Issue by iot-resister** [hzeller/gmrender-resurrect#221]
Awesome project!.  Thank you so much for maintaining this.    I'm running  on a headless raspberry pi with only X installed. No desktop environment and no window manager.   I can  stream  video  using open max player and an app like raspberry cast.  With gmrender,  I can  stream sound but no video shows. Is there a video dependency/player that I'm missing?  

here is my log output of a video only playing sound from a local file with upnpdroid ( all the filetype registrations removed):

https://pastebin.com/raw/w79gfHda

**Comment by mill1000** [comment]
Hi,

I've never actually used the video functionality and I don't have the time to dig into this right now. **But,** gmrender-resurrect uses gstreamer underneath to handle all it's decoding. So you may find answers searching around for gstreamer. I'd also try to play a video using the `gst-launch-1.0` command line tool and see if you can get that to work first.

**Comment by iot-resister** [comment]
I'm running 
`gst-launch  filesrc location=/home/pi/test.mp4`

and getting 
```
ERROR: from element /GstPipeline:pipeline0/GstFileSrc:filesrc0: Internal data flow error.
Additional debug info:
gstbasesrc.c(2625): gst_base_src_loop (): /GstPipeline:pipeline0/GstFileSrc:filesrc0:
streaming task paused, reason not-linked (-1)
````

**Comment by iot-resister** [comment]
@mill1000  Thanks for your help!   So after much trial and error I managed to get a video to play with this command

`gst-launch-1.0 playbin uri=file:///home/pi/test.mp4  video-sink="xvimagesink display=:0"`

the issue is making sure the sink is xvimagesink and its the correct display. Can I configure gmrender-resurrect  to use these settings ?

**Comment by iot-resister** [comment]
Hi @mill1000 

After a much trial and error I got the right options to play. 

`gst-launch-1.0 playbin uri=file:///home/pi/test.mp4  video-sink="xvimagesink display=:0 "  `

and the corresponding gmrender commad
`gmediarender  --friendly-name Test  --logfile=stdout --gstout-videosink="xvimagesink display=:0"`  

However, I seem to have lost sound,, which I assume is me figuring out the `--gstout-audiosink` option.  Also I cannot get full screen.

Thanks for your guidance!

**Comment by mill1000** [comment]
Try `autoaudiosink`, although I don't know why you'd have to manually specify it.

Also I noticed in your log the connmgr is only registering support for a single MIME type

> INFO  [2020-11-24 02:10:49.327869 | connmgr] Registering support for 'video/x-zmbv'

Are you aggressively filtering this on purpose? Otherwise it might be an indication that your gstreamer setup is wonky.

**Comment by iot-resister** [comment]
no I removed all the mimetypes from the logs to make them more readable.
