### ISSUE TITLE
Renderer does not list in proprietary apps such as Youtube, Amazon Music, Hbo Max etc..

### ISSUE THREAD

**Issue by gogsbread** [hzeller/gmrender-resurrect#225]
Wondering why the renderer would not list in the "connect to" outputs of popular apps such as YT, Amazon music etc.. I can stream to this renderer using BubbleUpnp or other generic servers. Is it because these proprietary apps handshake with a different protocol than uPnp? or is it because my renderer does not have something configured?

**Comment by mill1000** [comment]
Hi. In short, it is because those are proprietary protocols that are not compatible with UPnP. 

Unfortunately there are no open-source implementations of Google Cast or Amazon Cast that I am aware of. If you are a Spotify user there is this project: https://github.com/dtcooper/raspotify
