### ISSUE TITLE
Error with IPv6 address

### ISSUE THREAD

**Issue by ingo-h** [hzeller/gmrender-resurrect#228]
`gmediarender` does not start when connected to my IPv6 network. If I start it in the foreground with:

    ~$ OPENSSL_CONF="" /usr/bin/gmediarender --friendly-name Test --uuid 42 --gstout-initial-volume-db -20 --logfile /dev/stdout

it get stuck with endless repeating:

    ERROR [2021-01-26 20:13:12.397352 | upnp] UpnpInit(ip=(null), port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (59s)
    ERROR [2021-01-26 20:13:13.400272 | upnp] UpnpInit(ip=(null), port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (58s)
    ERROR [2021-01-26 20:13:14.403259 | upnp] UpnpInit(ip=(null), port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (57s)
    --- snip ---

When specifying the address with option  
`--ip-address 2003:d5:2736:dc00:dea6:32ff:fe7f:3846` on the command I get:

    ERROR [2021-01-26 20:17:13.203008 | upnp] UpnpInit(ip=2003:d5:2736:dc00:dea6:32ff:fe7f:3846, port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (59s)
    ERROR [2021-01-26 20:17:14.205936 | upnp] UpnpInit(ip=2003:d5:2736:dc00:dea6:32ff:fe7f:3846, port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (58s)
    ERROR [2021-01-26 20:17:15.208884 | upnp] UpnpInit(ip=2003:d5:2736:dc00:dea6:32ff:fe7f:3846, port=49494) Error: UPNP_E_SOCKET_ERROR (-208). Retrying... (57s)
    --- snip ---

How can I use IPv6 on gmrender-resurrect?

**Comment by hzeller** [comment]
Could you try the latest version from github ? The `--ip-address` has been replaced with `--interface-name` so you can specify the interface it should listen to. This uses a newer version of the initialization function of the upnp library.
It ultimately depends on if libupnp supports IPv6.

**Comment by ingo-h** [comment]
@hzeller Yes, I will try, but have to setup the compile environment on my Raspberry Pi. Do you know something about the status of IPv6 support of the upnp library?

**Comment by hzeller** [comment]
This will depend on if the library has been compiled with IPv6 support, i.e. [if ` UPNP_ENABLE_IPV6` is configured at compile time](https://github.com/pupnp/pupnp/blob/master/upnp/inc/upnpconfig.h.cm#L112).

**Comment by ingo-h** [comment]
I'm using Debian Buster. After `sudo apt install libupnp-dev` I find in libupnp-dev:

    /** Defined to 1 if the library has been compiled with ipv6 support
     *  (i.e. configure --enable-ipv6) */
    #define UPNP_ENABLE_IPV6 1

Also in `/usr/share/doc/libupnp13/changelog.Debian.gz` I find:

    pupnp-1.8 (1:1.8.1-1) unstable; urgency=medium

      * New upstream release.

      * debian/copyright:
        - Remove obsolete RSA section from copyright file.
      * debian/patches:
        - Drop patches applied upstream.
        - Refresh other patches.
      * debian/rules:
        - Drop --enable-ipv6 which is now the default.

     -- James Cowgill <jcowgill@debian.org>  Fri, 26 May 2017 09:22:52 +0100

This all means that libupnp supports IPv6 on my distribution. I will compile the current version of gmrender-resurrect now.

**Comment by coldtobi** [comment]
There is a gmrender-resurrect in Debian. Any reason not to use the packaged version?

**Comment by ingo-h** [comment]
@coldtobi This is what I find on my Raspberry Pi:

    rpi ~$ head -n1 /etc/apt/sources.list
    deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi

    rpi ~$ apt -a list gmediarender
    Listing... Done
    gmediarender/now 0.0.8-1~bpo10+1 armhf [installed,local]
    gmediarender/stable 0.0.7~git20180818.a7b0b1b-1 armhf

As you can see, from the repository on Buster is only version 0.0.7 available. This one is buggy because with the **stop** command the stream will not stop, only get silent. I do not want to waste network load for nothing. So I downloaded the source package version 0.0.8 from Debian Bullseye, compiled it on Buster and installed it `local`. That is the version with Error when using IPv6.

Why do you ask to use the version from Buster? Does it has no problems with IPv6? I haven't tested it before replacing it.

**Comment by hzeller** [comment]
Which reminds me, I should probably create a new release number that uses the new initialization, which makes it then easy for Debian to pick up.

**Comment by hzeller** [comment]
Created https://github.com/hzeller/gmrender-resurrect/releases/latest

**Comment by coldtobi** [comment]
@hzeller \o/ I've just uploaded it to Debian (so it will be in the unstable mirrors in a few hours.) And the timing is good (actually I was about to ask you about an release, because Debian is about to enter freeze for the Bullseye release soon.

> which makes it then easy for Debian to pick up.
Indeed. A release helps a lot to determine if a version has matured enough to be ready for a stable release.

**Comment by coldtobi** [comment]
> As you can see, from the repository on Buster is only version 0.0.7 available. This one is buggy because with the **stop** command the stream will not stop, only get silent. I do not want to waste network load for nothing. So I downloaded the source package version 0.0.8 from Debian Bullseye, compiled it on Buster and installed it `local`. That is the version with Error when using IPv6.
> 
> Why do you ask to use the version from Buster? Does it has no problems with IPv6? I haven't tested it before replacing it.

I'm not aware of any IPv6 related problems with the Debian package.
My question was aming to see if you know of some problems, so I could tackle them…

Regarding the IPV6 problem you see… Checking on my Debian unstable box, I see that gmediarender is listening on IPv6:
```
netstat -tulpen | grep gmediarender
tcp        0      0 10.xxx.xxx.xxx:49494      0.0.0.0:*               LISTEN      65534      634943     98809/gmediarender  
tcp6       0      0 :::49494                :::*                    LISTEN      65534      634944     98809/gmediarender  
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           65534      634947     98809/gmediarender  
udp        0      0 127.0.0.1:55319         0.0.0.0:*                           65534      634945     98809/gmediarender  

```
So unfortunately, I can't reproduce it here . (But Raspian is not Debian; there could be differences in how Raspian configured the upnp library, for instance)

**Comment by hzeller** [comment]
(off topic, Debian related: @coldtobi Yay it made it to my Debian unstable. There is a typo in the info message, it wants to say something like `now uses ...` but it says `no uses...`)

**Comment by coldtobi** [comment]
@hzeller oops! thanks for noticing!

**Comment by ingo-h** [comment]
@coldtobi Just see that you are the maintainer of the Debian package. Sorry, I'm a bit unfamiliar with the unstable box. Where is it? I've just cloned gmrender. Also off topic now: would you like to add a systemd service to the package? Bullseye is already giving a warning in the logs. Shall I open a new issue? I could make a suggestion.

**Comment by ingo-h** [comment]
Also the new version does not work with IPv6. These are my interfaces:

    rpi ~$ ip -br addr
    lo               UNKNOWN        127.0.0.1/8 ::1/128
    eth0             UP
    vlan24@eth0      UP             192.168.24.129/24
    vlan26@eth0      UP             2003:d5:272d:d100:dea6:32ff:fe01:dbec/64 fe80::dea6:32ff:fe01:dbec/64

For testing i have used two vlans to have both IP networks available. Now I start:

    rpi ~$ ./src/gmediarender --interface-name vlan24 --friendly-name Test --uuid 42 --gstout-initial-volume-db -20 --logfile /dev/stdout
    --- snip ---
    INFO  [2021-02-01 02:28:46.690091 | upnp] Registered IP=192.168.24.129 port=49494
    INFO  [2021-02-01 02:28:46.796052 | gstreamer] Query volume fraction: 0.100000
    INFO  [2021-02-01 02:28:46.796149 | control] Output initial volume is 0.100000; setting control variables accordingly.
    INFO  [2021-02-01 02:28:46.796284 | control] Setting volume-db to -20.00db == #50
    INFO  [2021-02-01 02:28:46.796645 | main] Ready for rendering.
    Ready for rendering.

`netstat` shows me:

    rpi ~$ sudo netstat -tulpen | grep gmediar
    tcp        0      0 192.168.24.129:49494    0.0.0.0:*               LISTEN      1000       28919      10816/./src/gmediar
    tcp6       0      0 :::49494                :::*                    LISTEN      1000       28920      10816/./src/gmediar
    udp        0      0 127.0.0.1:43980         0.0.0.0:*                           1000       28921      10816/./src/gmediar
    udp        0      0 0.0.0.0:1900            0.0.0.0:*                           1000       28923      10816/./src/gmediar

@coldtobi it's the same as you found with listening to **tcp6**. Did you started gmediarender on an interface with an IPv6 address, e.g. with option `--interface-name <ifipv6>`? If I do it, I get:

    rpi ~$ ./src/gmediarender --interface-name vlan26 --friendly-name Test --uuid 42 --gstout-initial-volume-db -20 --logfile /dev/stdout
    --- snip ---
    ERROR [2021-02-01 02:46:16.408430 | upnp] UpnpInit2(interface=vlan26, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (59s)
    ERROR [2021-02-01 02:46:17.410429 | upnp] UpnpInit2(interface=vlan26, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (58s)
    ERROR [2021-02-01 02:46:18.412722 | upnp] UpnpInit2(interface=vlan26, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (57s)
    --- snap ---

Seems it is a problem of gmrender-resurrect. Should be fixed before released in bullseye?

**Comment by hzeller** [comment]
gmrender-resurrect defers for these things to the libupnp, so that lib might not work with IPv6.

It does seem to listen on a tcp6 port though, so this is strange:
```
tcp6       0      0 :::49494                :::*                    LISTEN
```
so something is off. Either libupnp just listens on IPv6, but actually can't deal with it.

Might be worthwhile doing an `strace` on the startup of gmediarender and see what system calls it does and where it fails.

(I actually don't really know if IPv6 was considered at the time the UPnP standard was released, though it _should_ just work transparently).

**Comment by ingo-h** [comment]
I will have a look at `libupnp` with this simple test program: [Services and Control points using libupnp SDK for ubuntu 12.04](https://stackoverflow.com/a/56329389/5014688). I will update it to the latest versions.

**Comment by coldtobi** [comment]
@ingo-h :

> @coldtobi Just see that you are the maintainer of the Debian package. Also off topic now: would you like to add a systemd service to the package? Bullseye is already giving a warning in the logs. Shall I open a new issue? I could make a suggestion.

I'm aware of that, but while I've looked into that a year or so ago, I did not come up with a systemd .service file that provides the same amount of functionality: The init.d uses e.g /etc/default to set the instance name to the hostname: This was discussed in a unrelated Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941198#134 and there are also some hints how to solve that, but ENOTIME and the init.d still works; but I will accept pachtes ;)

> @coldtobi it's the same as you found with listening to tcp6. Did you started gmediarender on an interface with an IPv6 address, e.g. with option --interface-name <ifipv6>? If I do it, I get:

The interface on the PC had a IPv6 address associated, but generally my LAN is not setup for IPv6… 

But I can reproduce your issue; Once I've just removed the IPv4 adress, I'm getting the same error message. Searching for that,
I've ended up here: https://github.com/pupnp/pupnp/issues/110 … If I have both IPV4 and IPV6, the log only shows registration for the IPV4… Possibly your right and pupnp does not like IPV6 only devices…

@hzeller upnp's changelog mentions IPV6 at several points, so I guess it should support it…

stracing a bit into it looks like that it does indeed socket() bind() and listen() on the IPv6... (Did not further investigate it)

**Comment by coldtobi** [comment]
@ingo-h: PS: I just saw that upnp is already at version 1.14, while debian ist still at 1.8. Maybe worth a try to compile an updated libupnp… (I wont find time for it, though)

**Comment by ingo-h** [comment]
This issue is not a problem with **gmrender-resurrect**. It is a problem with the library **pupnp**. I have filed a bug report there: [The library does not work on IPv6 only networks](https://github.com/pupnp/pupnp/issues/218). Closing this issue here.
