### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by parasange** [hzeller/gmrender-resurrect#237]
I crated a new service file with
`sudo systemctl edit --force --full gemediarender.service`
and the following content:

```
[Unit]
Description=gmrender-resurrect service
After=network.target sound.target

[Service]
Environment="UPNP_DEVICE_NAME=Raspberry"
ExecStartPre=/bin/sh -c "/bin/systemctl set-environment UPNP_UUID=`ip link show | awk '/ether/ {print \"salt:)-\" $2}' | head -1 | md5sum | awk '{print $1}'`"

ExecStart=/usr/local/bin/gmediarender -f "$UPNP_DEVICE_NAME" -u "$UPNP_UUID" \
                                      --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault \
                                      --logfile=/tmp/gmediarenderer.log --gstout-initial-volume-db=-10
Restart=always

[Install]
WantedBy=multi-user.target
```
I then enabled it 
`sudo systemctl enable gmediarender`
and reload the daemon
`sudo systemctl daemon-reload`

After a reboot the service seems to be running, `ps -fC gmediarender` shows the process, but it does not seem to be recognized by pulseaudio-dlna on the other side.
Only when i restart the gmediarender service, it is recognized.
`sudo systemctl status gmediarender.service` gives:

```
● gmediarender.service - gmrender-resurrect service
   Loaded: loaded (/etc/systemd/system/gmediarender.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-13 22:02:43 BST; 3min 49s ago
 Main PID: 480 (gmediarender)
    Tasks: 80 (limit: 4322)
   CGroup: /system.slice/gmediarender.service
           └─480 /usr/local/bin/gmediarender -f Rasbpi4 -u ebcfc063ce3e00e3adf2967d6bf97743 --gstout-audiosink=alsasink --gsto

Jul 13 22:02:43 rasbpi4 systemd[1]: Starting gmrender-resurrect service...
Jul 13 22:02:43 rasbpi4 systemd[1]: Started gmrender-resurrect service.
Jul 13 22:02:56 rasbpi4 gmediarender[480]: Ready for rendering
```
Do you have any idea why it's not loading after boot?

**Comment by hzeller** [comment]
If you output the logs after the boot, what do you see ?
```
sudo journalctl -n50 -f -u gmediarender.service
```

**Comment by hzeller** [comment]
Maybe also add network-online.target as requirement ?
```
After=network.target network-online.target
```

**Comment by parasange** [comment]
> If you output the logs after the boot, what do you see ?
> 
> ```
> sudo journalctl -n50 -f -u gmediarender.service
> ```

I rebootet and seems to be fine
```
-- Logs begin at Wed 2021-07-14 07:26:55 BST. --
Jul 14 07:26:59 rasbpi4 systemd[1]: Starting gmrender-resurrect service...
Jul 14 07:26:59 rasbpi4 systemd[1]: Started gmrender-resurrect service.
Jul 14 07:27:11 rasbpi4 gmediarender[496]: Ready for rendering.
```

**Comment by parasange** [comment]
> Maybe also add network-online.target as requirement ?
> 
> ```
> After=network.target network-online.target
> ```

I edited the line `After=network.target network-online.target sound.target`, restarted the daemon and rebootet.
Unfortunately still no progress. Pulsaudio-dlna does not discover the renderer.

**Comment by parasange** [comment]
> > Maybe also add network-online.target as requirement ?
> > ```
> > After=network.target network-online.target
> > ```
> 
> I edited the line `After=network.target network-online.target sound.target`, restarted the daemon and rebootet.
> Unfortunately still no progress. Pulsaudio-dlna does not discover the renderer.

Log is again:
```
-- Logs begin at Wed 2021-07-14 07:35:49 BST. --
Jul 14 07:35:53 rasbpi4 systemd[1]: Starting gmrender-resurrect service...
Jul 14 07:35:53 rasbpi4 systemd[1]: Started gmrender-resurrect service.
Jul 14 07:36:05 rasbpi4 gmediarender[496]: Ready for rendering.
```

**Comment by hzeller** [comment]
if you have both interfaces connected (ethernet and wireless) it is probably unclear on which interface the renderer is listening; you can force that with `--interface-name`.

Can you pass `--logfile=stdout` to better see details, such as which IP address it binds to in the logfile ?

**Comment by parasange** [comment]
> --interface-nam



> if you have both interfaces connected (ethernet and wireless) it is probably unclear on which interface the renderer is listening; you can force that with `--interface-name`.
> 
> Can you pass `--logfile=stdout` to better see details, such as which IP address it binds to in the logfile ?

Sure, and thanks for your help so far.

I edited the service with
```
ExecStart=/usr/local/bin/gmediarender -f "$UPNP_DEVICE_NAME" -u "$UPNP_UUID" \
                                      --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault \
                                      --logfile=stdout --interface-name --gstout-initial-volume-db=-10
```
Is that correct?

`journalctl -n50` is now:
```

Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011384 | connmgr] Registering support for 'video/x-unaligned-raw'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011393 | connmgr] Registering support for 'video/x-vmnc'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011483 | connmgr] Registering support for 'video/x-vp3'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011492 | connmgr] Registering support for 'video/x-vp5'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011501 | connmgr] Registering support for 'video/x-vp6'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011511 | connmgr] Registering support for 'video/x-vp6-alpha'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011595 | connmgr] Registering support for 'video/x-vp6-flash'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011612 | connmgr] Registering support for 'video/x-vp8'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011621 | connmgr] Registering support for 'video/x-vp9'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011631 | connmgr] Registering support for 'video/x-wmv'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011640 | connmgr] Registering support for 'video/x-xan'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011726 | connmgr] Registering support for 'video/x-zmbv'
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.012008 | webserver] Provide /upnp/grender-64x64.png (image/png) from /usr/local/share/gmediarender/grender-64x64.png
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.014269 | webserver] Provide /upnp/grender-128x128.png (image/png) from /usr/local/share/gmediarender/grender-128x128.png
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.016994 | webserver] Provide /upnp/rendertransportSCPD.xml (text/xml) from buffer
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.017452 | webserver] Provide /upnp/renderconnmgrSCPD.xml (text/xml) from buffer
Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.018464 | webserver] Provide /upnp/rendercontrolSCPD.xml (text/xml) from buffer
Jul 14 07:51:17 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:51:17.019691 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (59s)
Jul 14 07:51:18 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:51:18.020883 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (58s)
...
Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.610892 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (0s)
Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.612716 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Giving up.
Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.612782 | main] ERROR: Failed to initialize UPnP device
Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Failed with result 'exit-code'.
Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Service RestartSec=100ms expired, scheduling restart.
Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Scheduled restart job, restart counter is at 1.
Jul 14 07:52:28 rasbpi4 systemd[1]: Stopped gmrender-resurrect service.
Jul 14 07:52:28 rasbpi4 systemd[1]: Starting gmrender-resurrect service...
Jul 14 07:52:29 rasbpi4 systemd[1]: Started gmrender-resurrect service.
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.087923 | main] gmediarender 0.0.9 log started [ gmediarender 0.0.9_git2021-03-14_4ac7d89 (libupnp-1.8.4; glib-2.58.3; gstreamer-1.14.4) ]
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.088053 | output] Using output module: gst (GStreamer multimedia framework)
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.116509 | gstreamer] Buffering disabled (--gstout-buffer-duration)
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.116596 | gstreamer] Setting audio sink to alsasink; device=sysdefault
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119736 | gstreamer] Set mute to off
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119829 | connmgr] Registering support for 'application/dash+xml'
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119848 | connmgr] Registering support for 'application/gxf'
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119862 | connmgr] Registering support for 'application/kate'
Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119873 | connmgr] Registering support for 'application/mxf'
...
```

**Comment by parasange** [comment]
> > --interface-nam
> 
> > if you have both interfaces connected (ethernet and wireless) it is probably unclear on which interface the renderer is listening; you can force that with `--interface-name`.
> > Can you pass `--logfile=stdout` to better see details, such as which IP address it binds to in the logfile ?
> 
> Sure, and thanks for your help so far.
> 
> I edited the service with
> 
> ```
> ExecStart=/usr/local/bin/gmediarender -f "$UPNP_DEVICE_NAME" -u "$UPNP_UUID" \
>                                       --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault \
>                                       --logfile=stdout --interface-name --gstout-initial-volume-db=-10
> ```
> 
> Is that correct?
> 
> `journalctl -n50` is now:
> 
> ```
> 
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011384 | connmgr] Registering support for 'video/x-unaligned-raw'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011393 | connmgr] Registering support for 'video/x-vmnc'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011483 | connmgr] Registering support for 'video/x-vp3'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011492 | connmgr] Registering support for 'video/x-vp5'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011501 | connmgr] Registering support for 'video/x-vp6'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011511 | connmgr] Registering support for 'video/x-vp6-alpha'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011595 | connmgr] Registering support for 'video/x-vp6-flash'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011612 | connmgr] Registering support for 'video/x-vp8'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011621 | connmgr] Registering support for 'video/x-vp9'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011631 | connmgr] Registering support for 'video/x-wmv'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011640 | connmgr] Registering support for 'video/x-xan'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.011726 | connmgr] Registering support for 'video/x-zmbv'
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.012008 | webserver] Provide /upnp/grender-64x64.png (image/png) from /usr/local/share/gmediarender/grender-64x64.png
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.014269 | webserver] Provide /upnp/grender-128x128.png (image/png) from /usr/local/share/gmediarender/grender-128x128.png
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.016994 | webserver] Provide /upnp/rendertransportSCPD.xml (text/xml) from buffer
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.017452 | webserver] Provide /upnp/renderconnmgrSCPD.xml (text/xml) from buffer
> Jul 14 07:51:16 rasbpi4 gmediarender[495]: INFO  [2021-07-14 07:51:16.018464 | webserver] Provide /upnp/rendercontrolSCPD.xml (text/xml) from buffer
> Jul 14 07:51:17 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:51:17.019691 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (59s)
> Jul 14 07:51:18 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:51:18.020883 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (58s)
> ...
> Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.610892 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Retrying... (0s)
> Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.612716 | upnp] UpnpInit2(interface=--gstout-initial-volume-db=-10, port=49494) Error: UPNP_E_INVALID_INTERFACE (-121). Giving up.
> Jul 14 07:52:28 rasbpi4 gmediarender[495]: ERROR [2021-07-14 07:52:28.612782 | main] ERROR: Failed to initialize UPnP device
> Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Main process exited, code=exited, status=1/FAILURE
> Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Failed with result 'exit-code'.
> Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 14 07:52:28 rasbpi4 systemd[1]: gmediarender.service: Scheduled restart job, restart counter is at 1.
> Jul 14 07:52:28 rasbpi4 systemd[1]: Stopped gmrender-resurrect service.
> Jul 14 07:52:28 rasbpi4 systemd[1]: Starting gmrender-resurrect service...
> Jul 14 07:52:29 rasbpi4 systemd[1]: Started gmrender-resurrect service.
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.087923 | main] gmediarender 0.0.9 log started [ gmediarender 0.0.9_git2021-03-14_4ac7d89 (libupnp-1.8.4; glib-2.58.3; gstreamer-1.14.4) ]
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.088053 | output] Using output module: gst (GStreamer multimedia framework)
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.116509 | gstreamer] Buffering disabled (--gstout-buffer-duration)
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.116596 | gstreamer] Setting audio sink to alsasink; device=sysdefault
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119736 | gstreamer] Set mute to off
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119829 | connmgr] Registering support for 'application/dash+xml'
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119848 | connmgr] Registering support for 'application/gxf'
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119862 | connmgr] Registering support for 'application/kate'
> Jul 14 07:52:29 rasbpi4 gmediarender[1240]: INFO  [2021-07-14 07:52:29.119873 | connmgr] Registering support for 'application/mxf'
> ...
> ```

Sorry noticed my mistake. I'll give you feedback in a minute

**Comment by hzeller** [comment]
and now you see it listening on ``Registered IP=192.168.0.108 port=49494` so that is where your upnp-controller will then discover it.

**Comment by parasange** [comment]
> and now you see it listening on `Registered IP=192.168.0.108 port=49494` so that is where your upnp-controller will then discover it.

Okay thanks.

But when I do a `pulseaudio-dlna --renderer-urls http://192.168.0.108:49494` 
it gives me a
`07-14 09:19:37 pulseaudio_dlna.holder                         WARNING  Could no connect to http://192.168.0.108:49494. Connection timeout.
`

Restarting the service without rebooting and starting `pulseaudio-dlna` and it works again. I don't get it :-)

**Comment by parasange** [comment]
I just added a delay for the service and now it works.
My systemd service now looks like

```
[Unit]
Description=gmrender-resurrect service
Requires=network-online.target sound.target
After=network-online.target sound.target

[Service]
Environment="UPNP_DEVICE_NAME=Rasbpi4"
ExecStartPre=/bin/sh -c "/bin/systemctl set-environment UPNP_UUID=`ip link show | awk '/ether/ {print \"salt:)-\" $2}' | head$
ExecStartPre=/bin/sleep 10
ExecStart=/usr/local/bin/gmediarender -f "$UPNP_DEVICE_NAME" -u "$UPNP_UUID" \
                                      --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault \
                                      --logfile=stdout --interface-name=wlan0 --gstout-initial-volume-db=-10
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by hzeller** [comment]
Independent of that you now worked around it with a little bit of waiting:
In the case of the hanging, connection timeout situation - do you see anything in the logs on the gmrender side ? It should output a message that shows an attempt to connect. But maybe that is not coming through.
Then looking on the network with wireshark might bring some insight.
