### ISSUE TITLE
Never shows up in media players when started before network ready

### ISSUE THREAD

**Issue by Mitschmaster** [hzeller/gmrender-resurrect#239]
When i start gmrender before my raspberry has fully established wifi connection it never shows up in media players.

**Comment by mill1000** [comment]
Are you using a systemd service? Do you have `After=network.target`? I haven't had any issues on my RPi3 that connects over WiFi.

My systemd service can be seen here: https://github.com/hzeller/gmrender-resurrect/issues/129#issuecomment-361453894

**Comment by Mitschmaster** [comment]
I did something similar and added `After=network-online.target` and `Wants=network-online.target`.
