### ISSUE TITLE
uPnP device undefined

### ISSUE THREAD

**Issue by Greeeeyyyss** [hzeller/gmrender-resurrect#249]
I'm using Ubuntu 14.04 LTS.
Following the installation page until I encountered the error upon running `make` command:

```make
make  all-recursive
make[1]: Entering directory `/home/greyz/gmrender-resurrect'
Making all in src
make[2]: Entering directory `/home/greyz/gmrender-resurrect/src'
(echo "#define GM_COMPILE_VERSION \"0.0.9_git2021-03-14_4ac7d89\"" >
git-version.h-new; \
        cmp -s git-version.h git-version.h-new || cp git-version.h-new git-version.h; \
        rm git-version.h-new)
gcc -std=gnu99  -g -O2 -Wall -Wpointer-arith -Wmissing-prototypes
-Wmissing-declarations -Wwrite-strings   -o gmediarender main.o
upnp_service.o upnp_control.o upnp_connmgr.o upnp_transport.o
song-meta-data.o variable-container.o upnp_device.o upnp_renderer.o
webserver.o output.o logging.o xmldoc.o xmlescape.o output_gstreamer.o
-pthread -lgthread-2.0 -lglib-2.0   -lgstreamer-1.0 -lgobject-2.0
-lglib-2.0   -pthread -lupnp -lthreadutil -lixml   -lm
upnp_device.o: In function `initialize_device':
/home/greyz/gmrender-resurrect/src/upnp_device.c:425: undefined
reference to `UpnpInit2'
/home/greyz/gmrender-resurrect/src/upnp_device.c:435: undefined
reference to `UpnpInit2'
collect2: error: ld returned 1 exit status
make[2]: *** [gmediarender] Error 1
make[2]: Leaving directory `/home/greyz/gmrender-resurrect/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/greyz/gmrender-resurrect'
make: *** [all] Error 2```

**Comment by hzeller** [comment]
Ubuntu 14.04 is very old and probably does not have a new enough upnp library.
You could compile a new libupnp on your system, or simply go back in time slightly for gmrender-resurrect that still calls the older version of the function.

If you have a checkout of gmrender-resurrect, just tell git in the directory to switch to that slightly older version:
```
git checkout 26d8f7edf5336bc30f7334c6ad459bf7f4f90ff2
```
Or if you prefer the zip file, get this version from https://github.com/hzeller/gmrender-resurrect/archive/26d8f7edf5336bc30f7334c6ad459bf7f4f90ff2.zip

**Comment by Greeeeyyyss** [comment]
@hzeller thank you, I was able to install and keep the renderer running and also discoverable. I cannot upgrade the Ubuntu version because it was on an old laptop with limited specs so the previous version and the zip file is very much appreciated!
