### ISSUE TITLE
Slow subscribe events

### ISSUE THREAD

**Issue by tommyzat** [hzeller/gmrender-resurrect#251]
Hello!
Event broadcasting is very slow (10 sec delay, sometimes even more)

**Comment by tommyzat** [comment]
This was fixed by replying with a status code 200 after each event.

**Comment by mill1000** [comment]
Glad to hear it.

Responding to events is required according to the [UPNP Device Arch](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf)

![image](https://user-images.githubusercontent.com/6924622/185974541-72c2047b-8150-4fdb-8630-e6eba17d05f8.png)

**Comment by tommyzat** [comment]
Thank you!
