### ISSUE TITLE
View connected users

### ISSUE THREAD

**Issue by tommyzat** [hzeller/gmrender-resurrect#253]
Hello!

How may I view if a user is connected to the UPNP server, or how many clients are listening, etc

**Comment by mill1000** [comment]
Both the UPNP media server and media renderer should implement the [ConnectionManager](http://upnp.org/specs/av/UPnP-av-ConnectionManager-v1-Service.pdf) service. The `GetCurrentConnectionIDs` action returns a list of ongoing connections and `GetCurrentConnectionInfo` can query info about a specific connection.

**Comment by tommyzat** [comment]
Thank you!

I tested with two Android clients (BubbleUPnP and Hi-Fi cast) and I couldn't get anything other than { ConnectionIDs: '0' }
Does this mean their implementation is incorrect, or is this the expected behaviour?

**Comment by mill1000** [comment]
I think this is expected. It's indicating the renderer only supports a single connection

**Comment by tommyzat** [comment]
Then there really is no way of knowing when a connection is truly over? I'm trying to find out when a client disconnects, since I get "stopped" notification from AVTransport when the music changes, not when, say, I change the renderer from bubbleupnp.

**Comment by mill1000** [comment]
A ConnectionID of 0 is a valid ID. You _might_ be able to get sufficient information out of the GetCurrentConnectionInfo action if it's implement properly.

Otherwise it might be better to query the media server.

**Comment by tommyzat** [comment]
I'm always getting the same result with GetCurrentConnectionInfo:
```
 {
   RcsID: '0',
   AVTransportID: '0',
   ProtocolInfo: ':::',
   PeerConnectionManager: '/',
   PeerConnectionID: '-1',
   Direction: 'Input',
   Status: 'Unknown'
}
```

I'm sorry I didn't quite understand what you meant by querying the media server...

**Comment by mill1000** [comment]
gmrender-resurrect is a media _renderer_ not a media server. What are you actually trying to accomplish?

**Comment by tommyzat** [comment]
I have a specific usecase in which I'm trying to figure out whether when a song is changed in the server, or whether a user actually disconnected from upnp. I receive "stopped" from AVTransport in both cases, but I'm not able to tell the difference between the two cases.

**Comment by mill1000** [comment]
Why not use a timeout when receiving `STOPPED` from AVTransport? If the song is being changed you'll receiving a `PLAYING` within a short time. If the user has "disconnected" (not sure that's really a valid concept in UPNP) there won't be another "PLAYING" event

**Comment by tommyzat** [comment]
This is currently my implementation indeed! However the time between "stopped" and "playing" varies between 1-10s and I have to use a high value, this is why I would have preffered another solution.

I appreciate your work on this library and thanks a lot for trying to help me out!
