### ISSUE TITLE
gmrender-resurrect not building with pupnp 1.14.13

### ISSUE THREAD

**Issue by claes** [hzeller/gmrender-resurrect#254]
gmrender-resurrect has stopped building for NixOS, and it appears to be due to a change in pupnp 1.14.13. The build failure is as below

        make[2]: Entering directory '/build/source/src'
        (echo "#define GM_COMPILE_VERSION \"0.0.9\"" > git-version.h-new; \
        cmp -s git-version.h git-version.h-new || cp git-version.h-new git-version.h; \
        rm git-version.h-new)
        gcc -DHAVE_CONFIG_H -I. -I..  -pthread -I/nix/store/kapyl9f6m06gwci858vvn1l9lzdsmlkn-glib-2.73.3-dev/include -I/nix/store/kapyl9f6m06gwci858vvn1l9lzdsmlkn-glib-2.73.3-dev/include/glib-2.0 -I/nix/store/3pnmicvvs0wn7biik3nrvwc6fvzbygdd-glib-2.73.3/lib/glib-2.0/include -I/nix/store/ljl76s7krknihwzlhyj82iia3jz9d9cm-gstreamer-1.20.3-dev/include/gstreamer-1.0 -I/nix/store/kapyl9f6m06gwci858vvn1l9lzdsmlkn-glib-2.73.3-dev/include -I/nix/store/kapyl9f6m06gwci858vvn1l9lzdsmlkn-glib-2.73.3-dev/include/glib-2.0 -I/nix/store/3pnmicvvs0wn7biik3nrvwc6fvzbygdd-glib-2.73.3/lib/glib-2.0/include -I/nix/store/wgxxb9f9hhi1f9mbkfyh6jivb2wshvmc-libupnp-1.14.13-dev/include/upnp -DPKG_DATADIR=\"/nix/store/jgnyxdz1n98cx9x419xm4anwhv8ckd4c-gmrender-resurrect-0.0.9/share/gmediarender\"   -g -O2 -Wall -Wpointer-arith -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -c -o main.o main.c
        main.c:46:10: fatal error: ithread.h: No such file or directory
           46 | #include <ithread.h>
              |          ^~~~~~~~~~~
        compilation terminated.
        make[2]: *** [Makefile:411: main.o] Error 1

and seems correlated with the pupnp change in https://github.com/pupnp/pupnp/commit/4dcfdba8470485d7b54a99c993808316b0d0b3cf

Failing build in NixOS Hydra:
https://hydra.nixos.org/build/189182614

I think this is a problem that will appear also in other distributions when they catch up with later versions of pupnp, thus reporting it upstream. 

Also discussed here: https://discourse.nixos.org/t/broken-nixpkgs-package-gmrender-resurrect/21908

**Comment by hzeller** [comment]
Let me see, it should be fairly easily be replaceable with pthread.

**Comment by hzeller** [comment]
Alright, updated, created new version tag, and nixpkgs update out for review.
