### ISSUE TITLE
daemon starts with Error: UPNP_E_INVALID_INTERFACE

### ISSUE THREAD

**Issue by passi999** [hzeller/gmrender-resurrect#257]
Hello,

I'm running gmediarender on an old PI A+ with an USB sound card. 
Starting the renderer manually by `sudo /etc/init.d/gmediarender start` works fine = BubbleUpnP will find the renderer and plays music on the USB sound card. 
Starting the renderer at startup will lead to the following error message in the logfile `ERROR [... | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (59s)` and BubbleUpnp will not find the renderer

To make sure that the daemon will be started only after network is available, I already added `$named` to the Required-start section. No change.
`# Required-Start: $remote_fs $syslog $named $all `

Stopping and Starting the daemon with `sudo systemctl stop gmediarender` will not solve the problem. It will not even change anything.

Killing the process with `sudo kill -9` and manually starting the deamon as described above will solve the issue.

I hope I'm not bothering you with some newbee configuration failure.

thanks for your support

Thanks & Regards

Passi

**Comment by passi999** [comment]
`ERROR [2022-12-30 11:22:15.411785 | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (59s)
ERROR [2022-12-30 11:22:16.417953 | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (58s)
ERROR [2022-12-30 11:22:17.422672 | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (57s)
ERROR [2022-12-30 11:22:18.427495 | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (56s)
ERROR [2022-12-30 11:22:19.432154 | upnp] UpnpInit2(interface=(null), port=49494) Error: UPNP_E_INVALID_INTERFACE (-12
1). Retrying... (55s)
INFO  [2022-12-30 11:22:19.767133 | upnp] Registered IP=192.168.1.42 port=49494
INFO  [2022-12-30 11:22:19.921126 | gstreamer] Query volume fraction: 0.100000
INFO  [2022-12-30 11:22:19.921515 | control] Output initial volume is 0.100000; setting control variables accordingly.
INFO  [2022-12-30 11:22:19.921734 | control] Setting volume-db to -20.00db == #50
INFO  [2022-12-30 11:22:19.923028 | main] Ready for rendering.`

**Comment by mill1000** [comment]
You seem to be mixing SysV init and systemd. I'd recommend going with systemd.

This issue has been reported a few times (#244, #239 and #129). You might find a solution in https://github.com/hzeller/gmrender-resurrect/issues/129#issuecomment-361453894

**Comment by passi999** [comment]
Thanks a lot.
I switched to systemd as you recommend and added a sleep as recomended in #129.
I learned that you must NOT use -d parameter, if you start gemediarender from systemd.
Works perfectly now.
