### ISSUE TITLE
Cut 0.1 release

### ISSUE THREAD

**Issue by almereyda** [hzeller/gmrender-resurrect#258]
There is a commit which indicates a 0.1 release of this marvel:

- 2a4d744814e3c824efa8665d91bffa6696836f43

Unfortunately this does not yet show up under the releases here:

- https://github.com/hzeller/gmrender-resurrect/releases

Are we able to cut the 0.1 release from the current git tree, and produce binary builds from it, without too much effort?

**Comment by hzeller** [comment]
Thanks for pointing that out, I only did the tag but forgot to make a release from it.

Release is out now: https://github.com/hzeller/gmrender-resurrect/releases/tag/v0.1

As for binary versions, it looks like some distributions already have picked up the version from the tag:

<a href="https://repology.org/project/gmrender-resurrect/versions">
<img src="https://repology.org/badge/vertical-allrepos/gmrender-resurrect.svg" alt="Packaging status">
</a>

**Comment by almereyda** [comment]
Many thanks for your responsiveness.
