### ISSUE TITLE
[Debian PowerPC G3] error in stdout when trying to play m3u8 stream

### ISSUE THREAD

**Issue by vareille** [hzeller/gmrender-resurrect#265]
I have this 25yo clamshell mac running Debian 8 (Jessie ~2008) linux 3.16 - This is a Big Endian machine.
Amazingly, it runs the latest release of libupnp (v1.14.18) and of gmrender-resurect (v0.1).
I have installed good, bad and ugly, and it plays everything flawlessly,
except for the m3u8 streams.

I attach the --logfile=stdout log:
[powerpcDebianClamshell.log](https://github.com/hzeller/gmrender-resurrect/files/13237613/powerpcDebianClamshell.log)

(Just to say that I know what I am doing, I have an x64/openbsd machine with the same setup that succesfully plays m3u8)

Here is the error:

ERROR [2023-11-02 11:06:12.400062 | gstreamer] hlsdemux0: Error: Could not determine type of stream (Debug: gsthlsdemux.c(903): _src_chain (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0)
ERROR [2023-11-02 11:06:14.892055 | gstreamer] hlsdemux0: Error: Could not determine type of stream (Debug: gsthlsdemux.c(903): _src_chain (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0)
ERROR [2023-11-02 11:06:17.856577 | gstreamer] hlsdemux0: Error: Could not determine type of stream (Debug: gsthlsdemux.c(903): _src_chain (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0)
ERROR [2023-11-02 11:06:20.995010 | gstreamer] hlsdemux0: Error: Could not determine type of stream (Debug: gsthlsdemux.c(903): _src_chain (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0)
ERROR [2023-11-02 11:06:21.001145 | gstreamer] hlsdemux0: Error: GStreamer encountered a general stream error. (Debug: gsthlsdemux.c(1240): gst_hls_demux_stream_loop (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0:
Could not fetch the next fragment: Internal data flow error.: gstbasesrc.c(2933): gst_base_src_loop (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstHLSDemux:hlsdemux0/GstSoupHTTPSrc:souphttpsrc0:
streaming task paused, reason not-negotiated (-4)
)

**Comment by mill1000** [comment]
This looks more like a problem within gstreamer. Can you play the stream successfully with a tool like `gst-play-1.0` or `gst-launch-1.0`?

e.g.
```
gst-play-1.0 http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourlw/bbc_radio_fourlw.isml/bbc_radio_fourlw-audio%3d48000.norewind.m3u8
```

**Comment by vareille** [comment]
I've tested it and you're right. I will contact them. thanks
