### ISSUE TITLE
main.c:47:21: fatal error: gst/gst.h: No such file or directory

### ISSUE THREAD

**Issue by feihualuomeng** [hzeller/gmrender-resurrect#76]
main.c:47:21: fatal error: gst/gst.h: No such file or directory

how issue this problem?
thanks

**Comment by hzeller** [comment]
This is the gstreamer header. You need to install the development packages. See INSTALL.md

**Comment by feihualuomeng** [comment]
i have already install libgstreamer0.10-dev, /usr/include/gstreamer-0.10 is extist
