### ISSUE TITLE
no sound and display is reverse

### ISSUE THREAD

**Issue by yangxuan8282** [hzeller/gmrender-resurrect#86]
I followed the  guide **INSTALL.md**,step by step finished the installation,use **GStreamer 1.0** on my RPI2,then I can found the render on android with app iMediaShare (BubbleUPnp  just can't find it,don't know why)
but after select the render to play a video,there is no sound,and display output is reverse 
any user face same issues?

**Comment by hzeller** [comment]
No sound or strange image problem are most likely a problem with gstreamer - it is the library that processes the media output. Gstreamer 1.0 is really old. Current version is 1.4 (or 1.5 development) - so you might want to upgrade to that first.

If it can't be found by BubbleUPNP, that is strange, I have to look at that.

**Comment by yangxuan8282** [comment]
@hzeller 
GStreamer current version in raspbian is 1.2,and I can found 1.4.5 in debian armhf mirror
but dependency problems is pain,there are dozens of package need to be downloaded
How can I update them quickly?

**Comment by yangxuan8282** [comment]
@hzeller 
hi,hzeller  I just have spent all day time to update gstreamer from 1.2 to 1.4
I use raspbian jessie mirror ,then use **apt-get** install those gstreamer realted package,which updated and installed over 200 package(so many dependency),maybe there are some better method,but haven't found it
after configure and build,I start the render over ssh(I don't have a keyboard for RPI) by 
    
    ./src/gmediarender -f "My Renderer"

now I can found the render on BubbleUPNP,but get some errors : 
 
    ERROR [2015-07-16 19:45:31.528718 | gstreamer] Failed to get track duration.
    ERROR [2015-07-16 19:46:58.376916 | gstreamer] glimagesink1: Error: Failed to connect to X display     server (Debug: gstgli
    magesink.c(458): _ensure_gl_setup ():     /GstPlayBin:play/GstPlaySink:playsink/GstBin:vbin/GstGLImageSink:glimagesink1)

**Comment by yangxuan8282** [comment]
and the render can't play sound either

**Comment by coldtobi** [comment]
Am Donnerstag, den 16.07.2015, 05:10 -0700 schrieb yangxuan8282:
> @hzeller 
> hi,hzeller  I just have spent all day time to update gstreamer from 
> 1.2 to 1.4
> I use raspbian jessie mirror ,then use **apt-get** install those 
> gstreamer realted package,which updated and installed over 200 
> package(so many dependency),maybe there are some better method,but 
> haven't found it
> after configure and build,I start the render over ssh(I don't have a 
> keyboard for RPI) by 
>     
>     ./src/gmediarender -f "My Renderer"
> 
> now I can found the render on BubbleUPNP,but get some errors : 
>  
>     ERROR [2015-07-16 19:45:31.528718 | gstreamer] Failed to get 
> track duration.
>     ERROR [2015-07-16 19:46:58.376916 | gstreamer] glimagesink1: 
> Error: Failed to connect to X display     server (Debug: gstgli
>     magesink.c(458): _ensure_gl_setup ():    
>  /GstPlayBin:play/GstPlaySink:playsink/GstBin:vbin/GstGLImageSink:gli
> magesink1)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hzeller/gmrender-resurrect/issues/86#issuecomment
> -121940214

Note that the gmediarender version in Jessie should be already built
against gstreamer 1.4, so a plain "apt-get install gmediarender" should
pull in all required dependenices, when using a Jessie mirror.
(note that your milage may vary as Raspian is not Debian, where I'm
maintaining gmediarender-resurrect)

Did you do an apt-get dist-upgrade or apt-get upgrade? This would
update every package on the system and could explain the amount of
packges you are seeing.

--
tobi

**Comment by yangxuan8282** [comment]
@coldtobi no,after change **wheezy** to **jessie** in **sources.list**,and do a **apt-get update**,then I just type:
   
    sudo apt-get install libgstreamer1.0-dev gstreamer1.0-alsa \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav

I think the **apt-get** automatically update and installed many unnecessary packages,and seems like there are no option for just update selected package,actually it's really like do a **apt-get upgrade**,,for it **REMOVE** 7 packages,but I am pretty sure the command is **apt-get install**

**Comment by yangxuan8282** [comment]
this is the removed packages:

    The following packages will be REMOVED:
      epiphany-browser gstreamer1.0-omx libgnome-desktop-3-2 libgraphite2-2.0.0 libharfbuzz0a libwayland0 wolfram-engine

**Comment by coldtobi** [comment]
Am Donnerstag, den 16.07.2015, 12:13 -0700 schrieb yangxuan8282:
> @coldtobi no,after change **wheezy** to **jessie** in 
> **sources.list**,and do a **apt-get update**,then I just type:
>    
>     sudo apt-get install libgstreamer1.0-dev gstreamer1.0-alsa \
>     gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
>     gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
>     gstreamer1.0-libav
> 
> I think the **apt-get** automatically update and installed many 
> unnecessary packages,and seems like there are no option for just 
> update selected package,actually it's really like do a **apt-get 
> upgrade**,,for it **REMOVE** 7 packages,but I am pretty sure the 
> command is **apt-get install**
> 

No, apt-get only does what it has been instructed to. When using apt
-get install <package>, its dependency resolver will only pull in
updates that are required for <package>. However, if you tell it to e.g
install libgstreamer1.0-dev, it will also install its dependencies.
Of course I do not know what you wanted to archive with your example,
but if you for example wnat to install gmediarender, just name this
package to avoid this. (But especially the gstreamer plugins have a
heavy dependency chain)

When you pull explictily pull in a dependency it can happen that other
packages' dependencies can no longer be resolved and the result can be
that the resolver finds only solutions when removing packages. I guess
that is what you've seeing here. 
You can try to assess this with aptitude's why-not feature.

apt-get upgrade will upgrade *all* packages to their latest version,
but never install new packages or remove packages, 
in contrast to apt-get dist-upgrade.

I usually use aptitude for tricky dependency situations. Its GI makes
it easier to assess the situation and also it provides also alternative
solutions when solving the dependencies.

Another note: It is not really recommended to mix packages from
different releases (Wheezy and Jessie), as things easily get
complicated. See also https://wiki.debian.org/FAQsFromDebianUser#How_da
ngerous_is_it_to_run_a_mixed_system.3F
It usually works, but you have expect some breakage.

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hzeller/gmrender-resurrect/issues/86#issuecomment
> -122054555


--
tobi
