### ISSUE TITLE
is logging to a remote server possible ?

### ISSUE THREAD

**Issue by webattitude** [hzeller/gmrender-resurrect#88]
I'm trying to avoid extra writes to sd card, on the pi, so I'd like to use a remote server for logging.
Is it possible ?

**Comment by hzeller** [comment]
Right now, logging just goes to a file, but you can modify it to use syslog instead (which then, in turn, can be configured to remotely log).
Place to start: src/logging.c

(and if you have done it, consider a pull request)

**Comment by webattitude** [comment]
It looks like rsyslog is already capable to send local log file to a remote server.
Thanks
