### ISSUE TITLE
Event detection mechanisms

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [hzeller/gmrender-resurrect#89]
Hi,
I was wondering if there's a way to detect when the renderer starts/stops playing an audio file. 
Currently I'm planning on having a shell script monitor gmediarenderer's log file for some predefined patterns (using `grep`).

I wanted to know the right way to accomplish this. 

**Use-case:**
Basically, I want to be able to switch ON an external amplifier when the renderer starts to stream and switch it OFF when the streaming is complete.

**Comment by hzeller** [comment]
You should be able to write a little UPnP program that just listens for events on the network; I have done a similar thing with this display ( https://github.com/hzeller/upnp-display ). It has the advantage that you don't even have to run it on the same machine.

Of course, it would be nice if such things could be done locally via some socket or something, but that is not implemented at this point.
