### ISSUE TITLE
After some time,renderer not visible on control point

### ISSUE THREAD

**Issue by Madhu205** [hzeller/gmrender-resurrect#94]
I implemented DLNA renderer using raspberry with gmrenderer-resurrect and gstreamer0.10. I implement control point on same raspberry using gupnp-tools(UPnP av control point). When i started control point it displays the various DLNA devices including Renderer.
After some time the Renderer device is invisible on control point UI with performing an action(playing a media file) or even without performing an action  and if i restart the control point the device is visible as usual. Why the device is not visible for some time?

**Comment by hzeller** [comment]
There were some bugs with really old versions of gstreamer 0.10 or 1.07 that made applications hang.
I'd suggest to first start using the latest version of gstreamer (the 1.0 version). The gstreamer0.10 is somewhat old and not maintained anymore.

Please re-open when you still see problems.
