### ISSUE TITLE
What are the supported media formats on gmrenderer.

### ISSUE THREAD

**Issue by Madhu205** [hzeller/gmrender-resurrect#95]
I implemented DLNA renderer using raspberry with gmrenderer-resurrect and gstreamer0.10. I implement control point on same raspberry using gupnp-tools(UPnP av control point). Its working fine with png,mp3,avi file formats transformation but when i choose jpeg,mp4 files from server to be played on renderer its not working.Doesn't it support those formats?

**Comment by hzeller** [comment]
If you start gmediarenderer with a logfile, you see all the plug-ins it registers and which formats it understands.

```
src/gmediarender --logfile=/dev/stdout
```

I would suggest to install gstreamer1.0 these days though; gstreamer0.10 is somewhat outdated.

**Comment by Madhu205** [comment]
I installed gstreamer1.0 also,whenever I tried to play JPG pictures I am getting 
**ERROR [2016-03-30 19:11:22.305271 | gstreamer] Failed to get track duration.
ERROR [2016-03-30 19:11:22.305349 | gstreamer] Failed to get track pos
**
and a gstreamer window opened,it contains a green background
![gmrender](https://cloud.githubusercontent.com/assets/17561588/14144156/3c47fd30-f6ac-11e5-9c6c-9d424b4b0bd8.png)

**Comment by hzeller** [comment]
gmrender is only really tested with music, not images - so this undefined behavior is expected. Having said that, it might not be to hard figuring out if it could work.
